# Nome da aplicação Spring
spring.application.name=taskflow

# URL do banco H2 em memória chamado taskflowdb
spring.datasource.url=jdbc:h2:mem:taskflowdb;DB_CLOSE_DELAY=-1

# Driver usado para conectar ao banco H2
spring.datasource.driver-class-name=org.h2.Driver

# Ativa o console web do H2 para acessar o banco pelo navegador
spring.h2.console.enabled=true

# Atualiza/cria as tabelas automaticamente conforme as entidades JPA
spring.jpa.hibernate.ddl-auto=update
