# Nome da aplicação Spring
spring.application.name=taskflow

# URL do banco PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflowdb

spring.datasource.username=postgres

spring.datasource.password=12Senha34

# Driver usado para conectar ao banco PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Atualiza/cria as tabelas automaticamente conforme as entidades JPA
spring.jpa.hibernate.ddl-auto=update
